export enum VALIDATE_ERROR_MESSAGE {
  INCORRECT_PROFILE_FIRSTNAME = 'INCORRECT_PROFILE_FIRSTNAME',
  INCORRECT_PROFILE_LASTNAME = 'INCORRECT_PROFILE_LASTNAME',
  INCORRECT_PROFILE_AGE = 'INCORRECT_PROFILE_AGE',
  NO_DATA = 'NO_DATA',
  SERVER_ERROR = 'SERVER_ERROR',
}
